name: Sarmalute
version: 1.0-SNAPSHOT
author: CoderDojo Ninja
main: ro.coderdojo.sarmalute.Main
commands:
  CoderDojo:
    description: Execute example command
    usage: /<command>
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
